# -*- coding: utf-8 -*-
"""(VGG16 Model) Transfer_Learning_Tumor_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-P6RyacIzAhDp4q_NXhBuCTOKtOLYJ5r

## Kidney Tumor Classification - Training
"""

import pandas as pd
import numpy as np
import os
import tensorflow as tf
import keras
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.vgg16 import preprocess_input
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

!wget -O archive.zip https://www.dropbox.com/scl/fi/hpx2whyirx0afa7btzvbc/archive.zip?rlkey=tv9fu1udy6d8zbrgqwf5wy7l7&st=5qdozeqx&dl=0

!unzip archive.zip

image_dimension = [224,224]
dataset_path = 'DATASET/train'

VGG_model = VGG16(input_shape= image_dimension+[3],weights='imagenet',include_top=False)

VGG_model.summary()

additional_layers = VGG_model.output
additional_layers = GlobalAveragePooling2D()(additional_layers)

additional_layers = Dense(1024,activation='relu')(additional_layers)
additional_layers = Dense(1024,activation='relu')(additional_layers)
additional_layers = Dense(512, activation='relu')(additional_layers)

output = Dense(2,activation='softmax')(additional_layers)

model = Model(inputs = VGG_model.input,outputs=output)

model.summary()

for layer in VGG_model.layers:
    layer.trainable = False

train_data_generator=ImageDataGenerator(preprocessing_function=preprocess_input)

train_generator=train_data_generator.flow_from_directory('DATASET/train',
                                                 target_size=(224,224),
                                                 color_mode='rgb',
                                                 batch_size=32,
                                                 class_mode='categorical',
                                                 shuffle=True)

model.compile(optimizer='Adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

train_step_size = train_generator.n // train_generator.batch_size

# Using `fit` instead of `fit_generator` as `fit` can handle generators in new TensorFlow/Keras versions.
r = model.fit(x=train_generator,
              steps_per_epoch=train_step_size,
              epochs=20)

# plot the loss
plt.plot(r.history['loss'], label='loss')
plt.title('Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend()
plt.show()
plt.savefig('Validation_Loss')

# plot the accuracy
plt.plot(r.history['accuracy'], label='accuracy')
plt.title('Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend()
plt.show()
plt.savefig('Validation_Accuracy')

from tensorflow.keras.models import load_model

model.save('tumor.h5')

from google.colab import drive
drive.mount('/content/drive')

from google.colab import files
files.download('tumor.h5')

"""## Prediction"""

import tensorflow as tf
from tensorflow.keras.preprocessing import image
import numpy as np
from tensorflow.keras.applications.vgg16 import preprocess_input
from tensorflow.keras.models import load_model

model = load_model('tumor.h5')

imge_path = 'DATASET/val/Normal/Normal- (10).jpg'

single_image = image.load_img(imge_path,target_size=(224,224))
x = image.img_to_array(single_image)

x = np.expand_dims(x,axis=0)
img_data = preprocess_input(x)

result = model.predict(img_data)
print(result)

if result[0][0] > result[0][1]:
    prediction = 'Not A Kidney Tumor'
else:
    prediction = 'Kidney Tumor'

print(prediction)

from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

val_data_generator=ImageDataGenerator(preprocessing_function=preprocess_input)

val_generator = val_data_generator.flow_from_directory(
    'DATASET/val',
    target_size=(224, 224),
    batch_size=32,
    class_mode='binary',
    shuffle=False
)

steps = val_generator.samples // val_generator.batch_size + int(val_generator.samples % val_generator.batch_size > 0)
img_data = model.predict(val_generator, steps=steps, verbose=1)

pred_classes = (img_data > 0.5).astype(int).flatten()
true_classes = train_generator.classes


pred_classes = np.argmax(img_data, axis=1)
true_classes = val_generator.classes

print(classification_report(true_classes, pred_classes))

conf_mat = confusion_matrix(true_classes, pred_classes)
plt.figure(figsize=(10, 7))
sns.heatmap(conf_mat, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()